---
name: Go
on: [push]
jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Run tests
        run: go test ./...

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Run tests
        run: go test ./...

      - name: Build Server & Client
        run: go build -v ./...

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get kubeconfig file from GKE
        uses: machine-learning-apps/gke-kubeconfig@master
        with:
          application_credentials: ${{ secrets.APPLICATION_CREDENTIALS }}
          project_id: ${{ secrets.PROJECT_ID }}
          location_zone: ${{ secrets.LOCATION_ZONE }}
          cluster_name: ${{ secrets.CLUSTER_NAME }}

      - name: Test Kubeconfig File
        uses: docker://bitnami/kubectl:latest
        with:
          args: get namespaces
        env:
          # Setting the environment variable KUBECONFIG sets the default config file that kubectl looks for.
          KUBECONFIG: '/github/workspace/.kube/config'
